# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: adb89a9d7e52f2890cb948e21509102a577f8d5de38012f4488eb56fe283026aabda3f25388fcf7846805057a3ffbee75907ba38eec80cedeb505aa6fd47d2dd

test:
  secret_key_base: bc01f1570d3a76fe9d91557f7cc27224df4acd2723fa65dc2bdf4917c35e5302a89aaaeec79e48194c24203b4b16c100b51754a27326789cd0b3aab1a0c1be3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
